version: 0.2

phases:
  pre_build:
    commands:
      - echo Cleaning up...
      - rm -rf node_modules package-lock.json build .npm
      - npm cache clean --force
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install --no-optional
      - echo Verifying gray-matter...
      - npm list gray-matter || echo "gray-matter not found"
      - ls node_modules/gray-matter || echo "gray-matter directory not found"
  build:
    commands:
      - echo Building the React app...
      - npm run build

artifacts:
  base-directory: build
  files:
    - '**/*'