version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - rm -rf node_modules package-lock.json
      - npm install
      - echo Verifying gray-matter installation...
      - ls -la node_modules | grep gray
      - npm list gray-matter
  build:
    commands:
      - echo Building the React app...
      - npm run build

artifacts:
  base-directory: build
  files:
    - '**/*'